// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVFg4cgxHYdzguVeyZB0mpOTOFHXHReTU',
    appId: '1:50633806529:web:0241576f7d32a84c00ba40',
    messagingSenderId: '50633806529',
    projectId: 'newchat-84140',
    authDomain: 'newchat-84140.firebaseapp.com',
    storageBucket: 'newchat-84140.firebasestorage.app',
    measurementId: 'G-7QDKCVWC4K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcAeFJPCYRyRiD0GmNle-Spa3jPdftydc',
    appId: '1:50633806529:android:09ed623087a734e300ba40',
    messagingSenderId: '50633806529',
    projectId: 'newchat-84140',
    storageBucket: 'newchat-84140.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsCQ1aiZZ-sFgdaUi98OTdmNmePsR3iWg',
    appId: '1:50633806529:ios:c76261b87d78685400ba40',
    messagingSenderId: '50633806529',
    projectId: 'newchat-84140',
    storageBucket: 'newchat-84140.firebasestorage.app',
    iosBundleId: 'com.example.newchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsCQ1aiZZ-sFgdaUi98OTdmNmePsR3iWg',
    appId: '1:50633806529:ios:c76261b87d78685400ba40',
    messagingSenderId: '50633806529',
    projectId: 'newchat-84140',
    storageBucket: 'newchat-84140.firebasestorage.app',
    iosBundleId: 'com.example.newchat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVFg4cgxHYdzguVeyZB0mpOTOFHXHReTU',
    appId: '1:50633806529:web:1bfb64d0a752af0900ba40',
    messagingSenderId: '50633806529',
    projectId: 'newchat-84140',
    authDomain: 'newchat-84140.firebaseapp.com',
    storageBucket: 'newchat-84140.firebasestorage.app',
    measurementId: 'G-DRZEMFWCJE',
  );
}
